## Álgebra Lineal Computacional - 2C 2022


### Arrays

Seguimos trabajando con matrices, veremos algunas funciones más, de Python y de Numpy en particular, para luego usar algunos comandos como **for** e **if**.


Importemos Numpy e ingresemos las matrices $$A = \begin{pmatrix} 0 & 1 & 2 \\ -3 & -4 & -5 \\ 6 & 7 & 8 \end{pmatrix} \quad B= \begin{pmatrix} 1 & 0 \\ 0 & -1 \\ 2 & 3 \end{pmatrix}$$
para aplicarles algunas funciones:

In [1]:
import numpy as np
A=np.array([[0,1,2],[-3,-4,-5], [6,7,8]])
B=np.array([[1,0], [0,-1], [2,3]])
print(A)
print(B)

[[ 0  1  2]
 [-3 -4 -5]
 [ 6  7  8]]
[[ 1  0]
 [ 0 -1]
 [ 2  3]]


### Transpuesta de una matriz

Si $A\in \mathbb{K}^{m\times n}$ la matriz transpuesta de $A$ es la matriz $A^t \in \mathbb{K}^{n\times m}$ que tiene por filas a las culumnas de $A$. 

$(A^t)_{ij}=a_{ji} \quad \forall 1\leq i\leq n, 1\leq j \leq m$.

La transpuesta de una matriz la calculamos agregando ".T" a la matriz. Calculemos $ A^t $ y $ (A.B)^t $. 

Recordar que multiplicamos matrices con "@".

In [2]:
At=A.T
ABt=(A@B).T
print(At)
print(ABt)

[[ 0 -3  6]
 [ 1 -4  7]
 [ 2 -5  8]]
[[  4 -13  22]
 [  5 -11  17]]


### Lugares de una matriz

En el ejercicio 3 de la práctica 1 practicaron cómo acceder a los distintos elementos de una matriz.

**IMPORTANTE: los índices en Python empiezan en 0**

Por ejemplo, para acceder al coeficiente $a_{i,j}$ de una matriz $A$ escribimos $A[i-1,j-1]$. 

Para acceder a una fila de $A$ usamos los dos puntos ":" que indican "todo". Por ejemplo, si queremos la fila $i$ de $A$ escribimos $A[i-1,:]$.

## Ejercicio

Calcular los siguientes elementos:
$a_{2,3}$, la fila 3 de $A$, la columna 1 de $A.B$, $(B^t)_{1,3}$

In [7]:
A@B

array([[  4,   5],
       [-13, -11],
       [ 22,  17]])

In [5]:
A23=A[1,2]
f3A=A[2,:]
c1AB=(A@B)[:,0]
Bt13=B.T[0,2]
print(A23)
print(f3A)
print(c1AB)
print(Bt13)

-5
[6 7 8]
[  4 -13  22]
2


### Inversa y determinante

El determinante es una función que se aplica a matrices **cuadradas** y devuelve por resultado un escalar.
$$A\in\mathbb{K}^{n\times n}, \quad det(A)\in\mathbb{K}$$
Esta función determina si una matriz cuadrada es inversible o no. Recordar que $A \in \mathbb{K}^{n\times n}$ es inversible $\iff \quad det(A)\neq 0$

Ambas funciones están en Numpy dentro del paquete "linalg". Por ejemplo:

In [9]:
d=np.linalg.det(A) #¿Es A inversible?
d 
#Entocnes A no es inversible

0.0

In [10]:
Ainv=np.linalg.inv(A) #Cuando la matriz no es inversible, se dice que es "singular"
Ainv

LinAlgError: Singular matrix

In [11]:
Binv=np.linalg.det(B) #si la matriz no es cuadrada salta un error

LinAlgError: Last 2 dimensions of the array must be square

### Funciones útiles y ciclos for:

Nos será útil en esta materia la función "range" para indicar rangos de valores para nuestras variables.
Por ejemplo

In [12]:
for i in range(10): 
    print(i)
print("Terminé") #Prestar atención a la indentación

0
1
2
3
4
5
6
7
8
9
Terminé


In [13]:
for i in range(1,5):
    print(i)

1
2
3
4


In [14]:
# Va de 2 en 2
for i in range(3,15,2):
    print(i)

3
5
7
9
11
13


Calculemos ahora su suma. Por ejemplo, para sumar los números naturales del 1 al 10 inclusive.
$$
\sum_{i=0}^{10} i
$$
Hacemos:

In [15]:
suma = 0
for i in range(0, 11):
    suma = suma + i
print("Suma: ", suma)

Suma:  55


## Ejercicio: 
Sumar los cuadrados de los números naturalesdel 5 al 1000 inclusive.
$$
\sum_{i=5}^{1000} i^2
$$
**Resultado**=333833470

In [17]:
suma = 0
for i in range(5, 1001):
    suma = suma + i*i
print("Suma: ", suma)

Suma:  333833470


### Sumar lugares de una matriz
Los elementos de la fila $i$ de una matriz $A \in \mathbb{K}^{m\times n}$ son $F_i=(a_{i1} \, a_{i2} \, \ldots \, a_{in})$, cuya suma $a_{i1}+a_{i2}+ \ldots + a_{in}$ se puede escribir usando una sumatoria:
$$S_i=\sum_{j=1}^{n}a_{ij}$$
Si queremos sumar **todos** los elementos de una matriz podemos sumar los resultados de las $m$ filas $S_1+S_2+ \ldots + S_m = \sum_{i=1}^{m} S_i$, quedando una doble sumatoria:
$$S=\sum_{i=1}^{m} \sum_{j=1}^{n}a_{ij}$$

## Ejercicio

Usar un ciclo for para calcular:

**a)** La suma de los elementos de la segunda fila de $A$. 

_La función **np.sum()** realiza la suma, la podemos usar para verificar nuestro resultado._

**b)** La traza de la matriz $A$, que es la suma de los elementos de la diagonal principal $tr(A)=\sum_{i=1}^n a_{ii}$.

_La función **np.trace()** realiza la suma, la podemos usar para verificar nuestro resultado._

**c)** La suma de todos los elementos de la matriz $B$ (vamos a necesitar dos ciclos, uno por cada sumatoria).

_La función **np.sum()** realiza la suma, la podemos usar para verificar nuestro resultado._


In [29]:
#a)
i = 0
suma = 0
for aij in A[i]:
    suma += aij
print("Suma:", suma, np.sum(A[i]))

#b)
i = 0
traza = 0
for i in range(len(A)):
    traza += A[i, i]
print("Traza:", traza, np.trace(A))

#c)
suma = 0
for row in A:
    for aij in row:
        suma += aij
print("Suma:", suma, np.sum(A))

Suma: 3 3
Traza: 4 4
Suma: 12 12


### Obs: 
La función **"len()"** de python puede ser útil por ejemplo para el ítem b). La función calcula la cantidad de elementos de una objeto. Por ejemplo, 

In [30]:
l=len([1,0,-3,2])
l

4

Como las matrices las ingresamos como un conjunto de filas, la función len me devolverá la cantidad de filas de la matriz. Por ejemplo,

In [31]:
for i in range(len(A)):
    print (A[i,i])  #¿Qué pasa si se lo aplicamos a la matriz B?

0
-4
8


Y como última observación, puede ser útil también en este caso, la función **"np.diag()"** que devuelve un vector con la diagonal principal de la matriz.

In [33]:
print(A)
dA=np.diag(A)
dB=np.diag(B)
print(dA)
print(dB)

[[ 0  1  2]
 [-3 -4 -5]
 [ 6  7  8]]
[ 0 -4  8]
[ 1 -1]


Veamos algunos ejemplos con **if**:

In [34]:
a = 15
b = 5
if(a>b):
    print(a, " es mayor que ", b)

15  es mayor que  5


In [35]:
# if - else
a = 15
b = 5
if(a>b):
    print(a, " es mayor que ", b)
else:
    print(a, " no es mayor que ", b)

15  es mayor que  5


In [36]:
# if - elif - else
a = 5
b = 5
if(a>b):
    print(a, " es mayor que ", b)
elif (b>a):
    print(b, " es mayor que ", a)
else:
    print(a, " es igual a ", b)

5  es igual a  5


## Ejercicios

**a)** Calcular la suma de los elementos arriba de la diagonal de $A$, o sea, calcular $$\sum_{i=1}^{m}\sum_{j>i}a_{ij}$$
**b)** Calcular el producto de los elementos no nulos de la matriz $A$.

In [49]:
suma_arriba_diag = 0
for i in range(len(A)):
    for j in range(i+1, len(A)):
        suma_arriba_diag += A[i, j]
print(suma_arriba_diag)

prod = 1
for row in A:
    for aij in row:
        if aij != 0:
            prod*=aij
print(prod)
A


-2
-40320


array([[ 0,  1,  2],
       [-3, -4, -5],
       [ 6,  7,  8]])

### Definir funciones

Por último, definamos algunas funciones. **¡¡En los "videos preliminares" en el campus tienen más detalles!!**

Por ejemplo:

In [50]:
def suma(a,b):
    c = a + b
    return(c)

In [51]:
suma(3,12)

15

Otro ejemplo:

In [52]:
def comparar(a, b):
    if(a>b):
        print(a, " es mayor que ", b)
    elif (b>a):
        print(b, " es mayor que ", a)
    else:
        print(a, " es igual a ", b)

In [53]:
comparar(3,12)

12  es mayor que  3


## Ejercicios

**a)** Realizar el Ejercicio 14 de la Práctica 1.

**b)** Escribir un programa que reciba un vector $v$ en $R^n$ y devuelva cuántas coordenadas de $v$ son mayores que 5.

_Obs: Recordar que puede ser útil la función "len" a la hora de usar "range" para recorrer todas las componentes de una lista.

In [ ]:
#completar