## Álgebra Lineal Computacional - 2C 2022


### Diagonalización

Veamos cómo trabajar en Numpy con los autovalores y los autovectores.

In [4]:
import numpy as np
import scipy 
from scipy.linalg import null_space #Lo vamos necesitar para calcular los núcleos de las matrices 

Primero veamos como ejemplo una de las matrices trabajadas en clase, así comparamos resultados.
Para $k=-7$ la matriz $A$ resultó:
$$A = \begin{pmatrix} -3 & 0 & 0 \\ -8 & 5 & -4 \\ -8 & 8 & -7 \end{pmatrix}=\begin{pmatrix} 1 & 0 & 0 \\ 1 & 2 & 1 \\ 0 & 1 & 1 \end{pmatrix}\begin{pmatrix} -3 & 0 & 0 \\ 0 & -3 & 0 \\ 0 & 0 & 1 \end{pmatrix}\begin{pmatrix} 1 & 0 & 0 \\ 1 & 2 & 1 \\ 0 & 1 & 1 \end{pmatrix}^{-1}$$

En la clase teórica les presentaron un método para calcular autovalores y autovectores, usando **np.linalg.eig()**, probémoslo:

In [19]:
A=np.array([[-3,0,0],[-8,5,-4],[-8,8,-7]])
e = np.linalg.eig(A) # e es una lista con dos elementos
print("Autovalores: ", e[0]) # El primer elemento es un array de autovalores
print("Autovectores: \n", e[1]) # El segundo elemento es una matriz con los autovectores normalizados como columnas.

Autovalores:  [-3.  1. -3.]
Autovectores: 
 [[ 0.          0.          0.74535599]
 [-0.4472136  -0.70710678  0.59628479]
 [-0.89442719 -0.70710678 -0.2981424 ]]


Es bastante diferente a lo que obtuvimos, sucede que además de tener los autovectores en otro orden, los mismos están normalizados, o sea miden 1 con la norma 2 (la euclídea), por ejemplo:
$$||(0,1,1)||=\sqrt{2}\Longrightarrow\frac{1}{\sqrt{2}}(0,1,1)=(0,\frac{1}{\sqrt{2}},\frac{1}{\sqrt{2}})\approx(0,0.7,0.7)$$
Por otro lado, hay otro par de autovectores de autovalor $-3$, ¿Por qué? ¿Está bien?

$E_{-3}$ es un plano en $\mathbb{R}^3$, Python nos dió otro par de generadores (de longitud 1) del mismo plano.

## Ejercicio
Calcular autovalores y autovectores de la matriz $A$ y decidir si es $A$ es diagonalizable en $\mathbb{R}$:
    $$A = \begin{pmatrix} 2 & 4 & -2 \\ 3 & 1 & 3 \\ -1 & -1 & 3 \end{pmatrix}$$

In [20]:
A=np.array([[2,4,-2],[3,1,3],[-1,-1,3]])
e = np.linalg.eig(A) 
print("Autovalores: ", e[0]) 
print("Autovectores: \n",e[1])

Autovalores:  [-2.+0.00000000e+00j  4.+1.43552999e-08j  4.-1.43552999e-08j]
Autovectores: 
 [[ 7.07106781e-01+0.00000000e+00j -7.07106781e-01-5.07536495e-09j
  -7.07106781e-01+5.07536495e-09j]
 [-7.07106781e-01+0.00000000e+00j -2.37879385e-17-5.07536495e-09j
  -2.37879385e-17+5.07536495e-09j]
 [-6.28472170e-17+0.00000000e+00j  7.07106781e-01+0.00000000e+00j
   7.07106781e-01-0.00000000e+00j]]


Qué fulero... Redondeemos los valores para ver mejor usando **np.round()**

In [22]:
print("Autovalores: ", np.round(e[0],2))#nos muestra 2 decimales en cada componente   
print("Autovectores: \n",np.round(e[1],2))

Autovalores:  [-2.+0.j  4.+0.j  4.-0.j]
Autovectores: 
 [[ 0.71+0.j -0.71-0.j -0.71+0.j]
 [-0.71+0.j -0.  -0.j -0.  +0.j]
 [-0.  +0.j  0.71+0.j  0.71-0.j]]


#### Atención: 
Vemos que $-2$ es autovalor simple, y $4$ es autovalor **doble**, dependemos entonces de $dim(E_4)$ para determinar si conseguimos una base de autovectores. El aspecto de los resultados es engañoso... ¿Por qué?
#### Consejo:
Si vamos a usar la calculadora de Numpy para trabajar, conviene calcular los autovectores usando **null_space** de la librería de **scipy.linalg** que importamos arriba.
Recordar que para hallar $E_4$ buscamos:
$$v\in\mathbb{R}^3 \quad \hbox{tales que}\quad Av=4v\Longleftrightarrow (A-4I)v=0$$
Por lo tanto buscamos el núcleo de $A-4I$:

In [26]:
A=np.array([[2,4,-2],[3,1,3],[-1,-1,3]])
a = np.linalg.eigvals(A)  #sólo nos calcula los autovalores 
print("Autovalores: ", np.round(a,2)) 
B=A-4*np.eye(3)
print("A-4I=\n",B)
E_4=null_space(B)
print("Autovectores de autovalor 4:\n",np.round(E_4,2))
C=A+2*np.eye(3)
E_2=np.round(null_space(C),2)

Autovalores:  [-2.+0.j  4.+0.j  4.-0.j]
A-4I=
 [[-2.  4. -2.]
 [ 3. -3.  3.]
 [-1. -1. -1.]]
Autovectores de autovalor 4:
 [[-0.71]
 [-0.  ]
 [ 0.71]]


¿Es $A$ diagonalizable?

No, porque 4 deberia tener 2 autovectores asociados

## Ejercicio
Calcular el término general de la sucesión $(a_n)_{n\in\mathbb{N}}$ dada por recurrencia:
    $$ \left\{ \begin{array}  Aa_1  = 1 \\ a_2 = 3 \\ a_{n+2}=3a_{n+1}-2a_n, \quad n\geq 1 \end{array} \right.$$
    
Observar que un término de la sucesión depende **linealmente** de los dos términos anteriores. Por ejemplo $a_3=-2a_1+3a_2$. Eso significa que podemos representar los términos de la sucesión de la siguiente manera:

$$ \begin{pmatrix} a_2 \\ a_3 \end{pmatrix}=\begin{pmatrix}  0 & 1 \\ -2 & 3 \end{pmatrix}\begin{pmatrix} a_1 \\ a_2 \end{pmatrix}$$
$$\Longrightarrow  \begin{pmatrix} a_3 \\ a_4 \end{pmatrix}=\begin{pmatrix}  0 & 1 \\ -2 & 3 \end{pmatrix}\begin{pmatrix} a_2 \\ a_3 \end{pmatrix}=\begin{pmatrix}  0 & 1 \\ -2 & 3 \end{pmatrix}^2\begin{pmatrix} a_1 \\ a_2 \end{pmatrix}$$

Siguiendo esta relación, queda que 

$$\begin{pmatrix} a_{n} \\ a_{n+1} \end{pmatrix}=\begin{pmatrix}  0 & 1 \\ -2 & 3 \end{pmatrix}^{n-1}\begin{pmatrix} a_1 \\ a_2 \end{pmatrix}$$

Por lo tanto, para calcular el término general $a_n$ podemos calcular $A^{n-1}$, siendo $A=\begin{pmatrix}  0 & 1 \\ -2 & 3 \end{pmatrix}$ 

Sabemos que si $A$ es diagonalizable, este cálculo es muy simple, porque si $A=C\cdot D\cdot C^{-1}$ entonces $A^{n-1}=C\cdot D^{n-1}\cdot C^{-1}$. Empecemos entonces diagonalizando la matriz:

In [27]:
A=np.array([[0,1],[-2,3]])
a=np.linalg.eigvals(A)
print(a) ####Podemos afirmar que es diagonalizable porque tiene 2 autovalores distintos!!! 

[1. 2.]


Sabemos así que $$A=C\cdot \begin{pmatrix}  1 & 0 \\ 0 & 2 \end{pmatrix}\cdot C^{-1} \Longrightarrow A^{n-1}=C\cdot \begin{pmatrix}  1 & 0 \\ 0 & 2 \end{pmatrix}^{n-1}\cdot C^{-1}\Longrightarrow A^{n-1}=C\cdot \begin{pmatrix}  1 & 0 \\ 0 & 2^{n-1} \end{pmatrix}\cdot C^{-1}$$
Calculemos los autovectores de $A$ para tener la matriz $C$:

In [29]:
E_1=null_space(A-a[0]*np.eye(2))
E_2=null_space(A-a[1]*np.eye(2))
print("Avec de aval 1:\n",np.round(E_1,2))#redondeamos para verlos más bonitos
print("Avec de aval 2:\n",np.round(E_2,2))

Avec de aval 1:
 [[0.71]
 [0.71]]
Avec de aval 2:
 [[0.45]
 [0.89]]


Antes de seguir armemos la matriz de autovectores $C$ y chequemos que no arrastramos grandes yerros calculando $C.A.C^{-1}$ y verificando que nos da $D$:

Para esto presentamos la función **np.append()** que agrega filas o columnas. Eso lo indicamos con **axis** (axis=0 agrega fila, axis=1 agrega columna).

In [30]:
C=np.empty((2,0),int) #Armamos una matriz vacía de dos filas y ninguna columna
C=np.append(C,E_1,axis=1) #A la matriz vacía C le agregamos en la primera columna el avec otenido de aval 1. 
C=np.append(C,E_2,axis=1) #A la matriz anterior le agremos el avec obtenido de aval 2.

C_1=np.linalg.inv(C)#la invertimos
print(np.round(C_1@A@C,2))#esto debería dar la matriz diagonal D con los aval. Redondeamos para ver mejor.

[[ 1.  0.]
 [-0.  2.]]


¿Cómo calculamos $a_n$? Recordar que:
$$\begin{pmatrix} a_{n} \\ a_{n+1} \end{pmatrix}=\begin{pmatrix}  0 & 1 \\ -2 & 3 \end{pmatrix}^{n-1}\begin{pmatrix} a_1 \\ a_2 \end{pmatrix}$$
Usando la diagonalización queda:
$$\begin{pmatrix} a_{n} \\ a_{n+1} \end{pmatrix}=C\cdot \begin{pmatrix}  1 & 0 \\ 0 & 2^{n-1} \end{pmatrix}\cdot C^{-1}\begin{pmatrix} a_1 \\ a_2 \end{pmatrix}$$
y recordando que $a_1=1$ y $a_2=3$, finalmente sabemos que $a_n$ será la primera componente de:
$$\begin{pmatrix} a_{n} \\ a_{n+1} \end{pmatrix}=C\cdot \begin{pmatrix}  1 & 0 \\ 0 & 2^{n-1} \end{pmatrix}\cdot C^{-1}\begin{pmatrix} 1 \\ 3 \end{pmatrix}$$

Si hacemos las cuentas a mano (recordar que Numpy nos da autovectores normalizados), tenemos que:
$$\begin{pmatrix} a_{n} \\ a_{n+1} \end{pmatrix}=\begin{pmatrix}  1 & 1 \\ 1 & 2\end{pmatrix}\cdot \begin{pmatrix}  1 & 0 \\ 0 & 2^{n-1} \end{pmatrix}\cdot \begin{pmatrix}  2 & -1 \\ -1 & 1 \end{pmatrix}\begin{pmatrix} 1 \\ 3 \end{pmatrix}$$
y multiplicando llegamos a $$a_n=-1+2^n, \quad \forall n\in\mathbb{N}$$



## Observación

Si $B=\{v_1,v_2,\dots,v_n\}$ es base de $\mathbb{K}^n$ formada por autovectores de una matriz $A$, sabemos que $A.v_1=\lambda_1.v_1$, ..., $A.v_n=\lambda_n.v_n$

Ahora cualquier vector $v\in\mathbb{K}^n$ se escribe de manera única como combinación de los vectores de la base (tenemos sus coordenadas en base B) y la transformación "multiplicar por A" es lineal:
$$v=a_1.v_1+a_2v_2+\cdots a_n.v_n \Longrightarrow A.v=A(a_1.v_1+a_2v_2+\cdots a_n.v_n) \Longrightarrow A.v=a_1.(A.v_1)+a_2.(A.v_2)+\cdots a_n.(A.v_n) $$ 
Usando que son autovectores tenemos que:
$$A.v=a_1\lambda_1.v_1+a_2.\lambda_2.v_2+\cdots a_n.\lambda_n.v_n $$ 
Así, $$A^2.v=A.A.v=A(a_1\lambda_1.v_1+a_2.\lambda_2.v_2+\cdots a_n.\lambda_n.v_n)=\dots= a_1\lambda_1^2.v_1+a_2.\lambda_2^2.v_2+\cdots a_n.\lambda_n^2.v_n$$
Y si seguimos, $$A^n.v=a_1\lambda_1^n.v_1+a_2.\lambda_2^n.v_2+\cdots a_n.\lambda_n^n.v_n$$

### Ejemplo:

Por ejemplo, sabiendo que $B=\{(1,1),(1,2)\}$ es base de autovectores de autovalores $1$ y $2$ respectivamente y que $(2,0)=4.(1,1)-2(1,2)$ (O sea que $(2,0)_B=(4,-2)$) tenemos por ejemplo que $A^n\begin{pmatrix} 2 \\ 0 \end{pmatrix}=4.A^n\begin{pmatrix} 1 \\ 1 \end{pmatrix} -2 A^n\begin{pmatrix} 1 \\ 2 \end{pmatrix}$. 
Como son autovectores queda que:
$$A^n\begin{pmatrix} 2 \\ 0 \end{pmatrix}=4.1^n\begin{pmatrix} 1 \\ 1 \end{pmatrix}+2^n\begin{pmatrix} 1 \\ 2 \end{pmatrix}$$

### Importante:
Del lado de la izquierda estamos haciendo potencias de matrices y del lado derecho potencias de NÚMEROS!!

## Ejercicio:

Diagonalizar la matriz $A=\begin{pmatrix} \frac{5}{4} & \frac{-3}{4} & 0 \\ \frac{-1}{4} & \frac{7}{4} & 0 \\ \frac{-1}{4} & \frac{7}{4} & 0 \end{pmatrix}$, calcular las coordenadas del vector $v=(-1,1,2)$ en la base de autovectores obtenida y usarlo para calcular $A^{20}.v$

In [10]:
A=np.array([[5/4,-3/4,0],[-1/4,7/4,0],[-1/4,7/4,0]])
a=np.linalg.eigvals(A)#calcular los autovalores
###Calcular los autoespacios asociados
E_0 = null_space(A-a[0]*np.eye(3))#Completar
E_2 = null_space(A-a[1]*np.eye(3))#Completar
E_1 = null_space(A-a[2]*np.eye(3))#Completar
### Armamos la matriz C de cambio de base E en la base de autovectores
C=np.empty((3,0),int) #Armamos una matriz vacía de 3 filas y ninguna columna
C= np.append(C, E_0, axis=1)#A la matriz vacía C le agregamos en la primera columna el avec otenido del primer aval. 
C= np.append(C, E_2, axis=1)#A la matriz de arriba C le agregamos en la segunda columna el avec otenido del segundo aval.
C= np.append(C, E_1, axis=1)#Y acá la tercera columna
b=np.array([-1,1,2])
coords=np.linalg.solve(C,b) #Buscamos las coordenadas de v en la base de autovectores
###Y ahora qué cuenta tendríamos que hacer? Revisar el ejemplo de arriba!!!

In [27]:
A20v = coords[0]*(a[0]**20*C[:,0])+ coords[1]*(a[1]**20*C[:,1]) + coords[2]*(a[2]**20*C[:,2])

In [28]:
A20v

array([-1048576.,  1048576.,  1048576.])

In [29]:
coords[0]*C[:,0] + coords[1]*C[:,1] + coords[2]* C[:,2]

array([-1.,  1.,  2.])