In [14]:
import numpy as np

# Acá les dejo un regalito. 
# Para que todo lo que printeamos tenga 3 decimales y sin notación científica
np.set_printoptions(precision=3)
np.set_printoptions(suppress=True)

Defino algunas funciones que nos van a servir

In [15]:
def matriz_ruina_apostador(n,p):
    """Devuelve la matriz de transición de la ruina del apostador 
    de tamaño nxn, cuando se gana con probabilidad p"""
    
    A = np.zeros((n,n))
    A[0,0] = 1
    A[-1,-1] = 1
    for j in range(1,n-1):
        A[j-1,j] = 1-p
        A[j+1,j] = p
    return(A)

In [16]:
def p_inf_v(P, v ,k , tol = 10**-6):
    """Itera v = P@v hasta que converja o se llegue a k iteraciones.
    tol es como el espilón del límite, si la distancia entre dos iteraciones
    consecutivas es menor a tol consideramos que llegamos al límite"""
    
    for i in range(k):
        if np.linalg.norm(P @ v - v) < tol:
            break
        else:
            v = P @ v
    return(v)

In [17]:
def canonico(n,j):
    """Devuelve el canoninco e_j de R^n"""

    v = np.zeros(n)
    v[j] = 1
    return(v)

## Tenis

In [5]:
#Armo la matriz de proceso
n=5
p=2/3

P = matriz_ruina_apostador(n,p)
print(P)


[[1.    0.333 0.    0.    0.   ]
 [0.    0.    0.333 0.    0.   ]
 [0.    0.667 0.    0.333 0.   ]
 [0.    0.    0.667 0.    0.   ]
 [0.    0.    0.    0.667 1.   ]]


In [6]:
# Estado inicial 40-40 (deuce), o sea el tercer canoninco
v =  canonico(n,2) # Acuerdense que python cuenta desde 0
print(v)

[0. 0. 1. 0. 0.]


In [7]:
# Iteramos
v_inf = p_inf_v(P,v,1000)
print(v_inf)

[0.2 0.  0.  0.  0.8]


In [8]:
# Cómo se escribe v en base de autovectores?

Cbe = np.linalg.eig(P)[1]
np.linalg.solve(Cbe,v)

array([0.2  , 0.8  , 1.275, 0.778, 0.   ])

In [9]:
# Cómo se ve P^inf

P_inf = np.linalg.matrix_power(P,1000)
print(P_inf)

[[1.    0.467 0.2   0.067 0.   ]
 [0.    0.    0.    0.    0.   ]
 [0.    0.    0.    0.    0.   ]
 [0.    0.    0.    0.    0.   ]
 [0.    0.533 0.8   0.933 1.   ]]


¿Qué nos dicen las columnas de $ P^\infty $ ?

## Figuritas

In [22]:
def matriz_figuritas(n):
    """Devuelve la matriz de transición para el problema de n figuritas"""
    
    diag = np.linspace(0,1,n+1) # esto me arma la suc k/n con k de 0 hasta n
    
    # Armo una matriz diagonal con diag en la diagonal
    P = np.diag(diag)

    # abajo de la diagonal recorro la suc k/n al revés desde n hasta 1
    for i in range(1,n+1):
        P[i,i-1] = diag[-i] 
    return(P)

In [23]:
P = matriz_figuritas(638)
v = canonico(639,0)

In [27]:
P

array([[0.   , 0.   , 0.   , ..., 0.   , 0.   , 0.   ],
       [1.   , 0.002, 0.   , ..., 0.   , 0.   , 0.   ],
       [0.   , 0.998, 0.003, ..., 0.   , 0.   , 0.   ],
       ...,
       [0.   , 0.   , 0.   , ..., 0.997, 0.   , 0.   ],
       [0.   , 0.   , 0.   , ..., 0.003, 0.998, 0.   ],
       [0.   , 0.   , 0.   , ..., 0.   , 0.002, 1.   ]])

In [12]:
# Itero hasta que la última coordeanda de v sea mayor o igual a 0.9
# y cuento cuantas figuritas compre
figus = 0
while v[-1] < 0.9:
    v = P @ v
    figus += 1 # esto equivale a figus = figus + 1
print(figus)
print(v[-5:])

5553
[0.    0.    0.005 0.095 0.9  ]


In [13]:
# Suponiendo 5 figuritas por paquete:
print('Neccesito comprar', round(figus/5), 'paquetes para tener un 90% de probabilidades de llenar el álbum')

Neccesito comprar 1111 paquetes para tener un 90% de probabilidades de llenar el álbum


### ¿Se les ocurren otros juegos o problemas que se puedan modelar con procesos de Markov?