In [73]:
from scipy.linalg import null_space
import numpy as np
from numpy.linalg import eigvals, norm, inv
import matplotlib.pyplot as plt

In [79]:
np.set_printoptions(precision=3)
np.set_printoptions(suppress=True)

### Ejercicio 3: Fibonacci

In [3]:
A = np.array([[0,1],[1,1]])

In [4]:
l2, l1 = eigvals(A)
e1 = np.array([1,l1]) #null_space(A-l1*np.eye(2))
e2 = np.array([1,l2]) #null_space(A-l2*np.eye(2))

CBE = np.array([e1,e2]).T
D = np.array(([l1, 0], [0, l2]))
CEB = inv(CBE)

In [5]:
np.round(CBE@D@CEB)

array([[-0.,  1.],
       [ 1.,  1.]])

In [6]:
def mi_super_formula_de_fibonacci(n):
    return int((-l1**n+l2**n)/(l2-l1))

for n in range(10):
    print(mi_super_formula_de_fibonacci(n))


0
1
1
2
3
5
8
13
21
34


# Markov

In [69]:
def p_inf_v(P, v ,k , tol = 10**-6):
    """Itera v = P@v hasta que converja o se llegue a k iteraciones.
    tol es como el espilón del límite, si la distancia entre dos iteraciones
    consecutivas es menor a tol consideramos que llegamos al límite"""
    
    for i in range(k):
        if np.linalg.norm(P @ v - v) < tol:
            break
        else:
            v = P @ v
    return(v)

### Ejercicio 17: Ratones

In [11]:
A = (1/4) * np.array([[1,2,2,2], [1,2,0,0], [1,0,2,0], [1,0,0,2]])
avals = eigvals(A)
avecs = [null_space(A - l*np.eye(4)) for l in avals]

In [16]:
v = [20,0,0,0]
for i in range(4):
    v = A@v
v

array([8.046875, 3.984375, 3.984375, 3.984375])

In [33]:
A = (1/4) * np.array([[1,2,2,2], [1,2,0,0], [1,0,2,0], [1,0,0,2]])
for i in range(5):
    A = A@A
print(A)

[[0.4 0.4 0.4 0.4]
 [0.2 0.2 0.2 0.2]
 [0.2 0.2 0.2 0.2]
 [0.2 0.2 0.2 0.2]]


### Ejercicio 18: Borracho

In [62]:
def matriz_de_transicion(n,p):
    """Devuelve la matriz de transición cuando la probabilidad
    de ir para casa es p y la distancia es de n
    """
    
    A = np.zeros((n,n))
    A[0,0] = 1
    A[-1,-1] = 1
    for j in range(1,n-1):
        A[j-1,j] = p
        A[j+1,j] = 1-p

    return A

In [94]:
def calcular_estado_limite(n, p, ei):
    P = matriz_de_transicion(n,p)
    v = np.zeros(n)
    v[ei] = 1
    return p_inf_v(P, v, 10000)

#### Seria interesante calcular la probabilidad de quedarse en casa como una funcion de ei y p

In [97]:
limite = calcular_estado_limite(20, 1/2, 10)
print(f"Con un {limite[0]*100}% de probabilidades termina en casa")
print(f"Con un {limite[n-1]*100}% de probabilidades termina en el bar")

Con un 47.368323441321245% de probabilidades termina en casa
Con un 52.631479986358876% de probabilidades termina en el bar


In [98]:
limite = calcular_estado_limite(20, 0.8, 10)
print(f"Con un {limite[0]*100}% de probabilidades termina en casa")
print(f"Con un {limite[n-1]*100}% de probabilidades termina en el bar")

Con un 99.99950424862773% de probabilidades termina en casa
Con un 0.0003814691861656787% de probabilidades termina en el bar


In [101]:
limite = calcular_estado_limite(20, 1/2, 1)
print(f"Con un {limite[0]*100}% de probabilidades termina en casa")
print(f"Con un {limite[n-1]*100}% de probabilidades termina en el bar")

Con un 94.73674467762108% de probabilidades termina en casa
Con un 5.263059119935287% de probabilidades termina en el bar
